name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: Nizamuddin1N
          outputs: dist/snake.svg

      - name: Deploy Snake Animation to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          folder: dist
